repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^((viseron|tests)/.+)?[^/]+\.py$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
      - id: codespell
        args:
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
        exclude_types: [csv, json]
        exclude: ^tests/fixtures/
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - pycodestyle==2.7.0
          - pyflakes==2.3.1
          - flake8-docstrings==1.6.0
          - pydocstyle==6.0.0
          - flake8-comprehensions==3.5.0
          - flake8-noqa==1.1.0
          - mccabe==0.6.1
        files: ^(viseron|tests)/.+\.py$
