---
- name: Build and deploy Viseron
  hosts: production-nodes
  tasks:
    - name: Copy viseron to server
      synchronize:
        src: /mnt/cache/appdata/viseron
        dest: /opt/dev
        dirs: yes
        rsync_opts:
          - "--exclude=config"
          - "--exclude=recordings"
          - "--exclude=docker-compose.yaml"
      register: syncstatus
      failed_when:
        - syncstatus.rc != 0
        - syncstatus.rc != 32
#    - name: Build Viseron container
#      docker_compose:
#        project_src: /opt/docker/viseron
#        build: yes
#        state: present
