name: CI

on:
  push:
    branches:
      - dev
      - master
  pull_request: ~

env:
  CACHE_VERSION: 1
  PYTHON_VERSION: 3.8
  PRE_COMMIT_CACHE: ~/.cache/pre-commit

jobs:
  prepare-pre-commit:
    name: Prepare pre-commit
    runs-on: ubuntu-latest
    steps:
      # Create Python virtual env used for linters
      - name: Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      # Create a virtual environment and cache it 
      - name: Restore Python virtual environment
        id: cache-venv
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-python-venv
        with:
          path: venv
          key: >-
            ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-
            ${{ runner.os }}-prepare-pre-commit-
            ${{ runner.os }}-
      - name: Create Python virtual environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements_test.txt
      # Install pre-commit hooks into the cached virtual environment
      - name: Cache pre-commit Python virtual env
        id: cache-pre-commit
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-pre-commit
        with:
          path: ${{ env.PRE_COMMIT_CACHE }}
          key: >-
            ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-
            ${{ runner.os }}-prepare-pre-commit-
            ${{ runner.os }}-
      - name: Install pre-commit and its dependencies
        if: steps.cache-pre-commit.outputs.cache-hit != 'true'
        run: |
          . venv/bin/activate
          pre-commit install-hooks

  run-isort:
    name: Run isort
    runs-on: ubuntu-latest
    needs: prepare-pre-commit
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2.2.2
        id: python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Restore base Python virtual environment
        id: cache-venv
        uses: actions/cache@v2.1.6
        with:
          path: venv
          key: ${{ runner.os }}-prepare-pre-commit-cache-python-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Fail job if Python cache restore failed
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          echo "Failed to restore Python virtual environment from cache"
          exit 1
      - name: Restore pre-commit environment from cache
        id: cache-pre-commit
        uses: actions/cache@v2.1.6
        with:
          path: ${{ env.PRE_COMMIT_CACHE }}
          key: ${{ runner.os }}-prepare-pre-commit-cache-pre-commit-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Fail job if pre-commit cache restore failed
        if: steps.cache-pre-commit.outputs.cache-hit != 'true'
        run: |
          echo "Failed to restore pre-commit environment from cache"
          exit 1
      - name: Run isort
        run: |
          . venv/bin/activate
          pre-commit run --hook-stage manual isort --all-files --show-diff-on-failure
