name: CI

on:
  push:
    branches:
      - dev
      - master
  pull_request: ~

env:
  CACHE_VERSION: 1
  PYTHON_VERSION: 3.8
  PRE_COMMIT_CACHE: ~/.cache/pre-commit
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  BUILDKIT_PROGRESS: plain

jobs:
  prepare-python-venv:
    name: Prepare Python venv
    runs-on: ubuntu-latest
    steps: 
      # Create Python virtual env used for linters
      - name: Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      # Create a virtual environment and cache it 
      - name: Restore Python virtual environment
        id: cache-venv
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-python-venv
        with:
          path: venv
          key: >-
            ${{ runner.os }}-prepare-python-venv-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('requirements_ci.txt') }}
          restore-keys: |
            ${{ runner.os }}-prepare-python-venv-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-prepare-python-venv-${{ env.cache-name }}-
            ${{ runner.os }}-prepare-python-venv-
            ${{ runner.os }}-
      - name: Create Python virtual environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements_ci.txt

  prepare-pre-commit:
    name: Prepare pre-commit
    runs-on: ubuntu-latest
    needs: prepare-python-venv
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2.2.2
        id: python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Restore base Python virtual environment
        id: cache-venv
        uses: actions/cache@v2.1.6
        with:
          path: venv
          key: ${{ runner.os }}-prepare-python-venv-cache-python-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('requirements_ci.txt') }}
      - name: Fail job if Python cache restore failed
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          echo "Failed to restore Python virtual environment from cache"
          exit 1
      # Install pre-commit hooks into the cached virtual environment
      - name: Cache pre-commit Python virtual env
        id: cache-pre-commit
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-pre-commit
        with:
          path: ${{ env.PRE_COMMIT_CACHE }}
          key: >-
            ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('requirements_ci.txt') }}
          restore-keys: |
            ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-prepare-pre-commit-${{ env.cache-name }}-
            ${{ runner.os }}-prepare-pre-commit-
            ${{ runner.os }}-
      - name: Install pre-commit hooks
        if: steps.cache-pre-commit.outputs.cache-hit != 'true'
        run: |
          . venv/bin/activate
          pre-commit install-hooks

  run-isort:
    name: Run isort
    runs-on: ubuntu-latest
    needs: prepare-pre-commit
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2.2.2
        id: python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Restore base Python virtual environment
        id: cache-venv
        uses: actions/cache@v2.1.6
        with:
          path: venv
          key: ${{ runner.os }}-prepare-python-venv-cache-python-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('requirements_ci.txt') }}
      - name: Fail job if Python cache restore failed
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          echo "Failed to restore Python virtual environment from cache"
          exit 1
      - name: Restore pre-commit environment from cache
        id: cache-pre-commit
        uses: actions/cache@v2.1.6
        with:
          path: ${{ env.PRE_COMMIT_CACHE }}
          key: ${{ runner.os }}-prepare-pre-commit-cache-pre-commit-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('requirements_ci.txt') }}
      - name: Fail job if pre-commit cache restore failed
        if: steps.cache-pre-commit.outputs.cache-hit != 'true'
        run: |
          echo "Failed to restore pre-commit environment from cache"
          exit 1
      - name: Run isort
        run: |
          . venv/bin/activate
          pre-commit run --hook-stage manual isort --all-files --show-diff-on-failure


  run-pytest:
    name: Run Pytest
    runs-on: ubuntu-latest
    needs: prepare-python-venv
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2.2.2
        id: python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Restore base Python virtual environment
        id: cache-venv
        uses: actions/cache@v2.1.6
        with:
          path: venv
          key: ${{ runner.os }}-prepare-python-venv-cache-python-venv-${{ env.CACHE_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('requirements_ci.txt') }}
      - name: Fail job if Python cache restore failed
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          echo "Failed to restore Python virtual environment from cache"
          exit 1
      - name: Pull current Docker dev tag 
        run: |
          docker-compose --file azure-pipelines/docker-compose-build.yaml --env-file azure-pipelines/.env pull amd64-viseron
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v7
      - name: Re-build wheels if requirements.txt has changed
        if: contains(steps.changed-files.outputs.modified_files, 'requirements.txt')
        run: |
          docker-compose --file azure-pipelines/docker-compose-build.yaml --env-file azure-pipelines/.env pull amd64-wheels
          docker-compose --file azure-pipelines/docker-compose-build.yaml --env-file azure-pipelines/.env build --build-arg BUILDKIT_INLINE_CACHE=1 amd64-viseron-wheels
          docker-compose --file azure-pipelines/docker-compose-build.yaml --env-file azure-pipelines/.env build --build-arg BUILDKIT_INLINE_CACHE=1 amd64-viseron
      - name: Build Pytest Docker image
        run: |
          docker-compose --file azure-pipelines/docker-compose-build.yaml --env-file azure-pipelines/.env build --build-arg BUILDKIT_INLINE_CACHE=1 amd64-viseron-tests
      - name: Run Pytest
        run: |
          docker-compose --file azure-pipelines/docker-compose-build.yaml --env-file azure-pipelines/.env up amd64-viseron-tests
      - name: Copy .coverage to host
        run: |
          docker cp amd64-viseron-tests:/src/coverage.xml coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.5.2

