parameters:
  - name: architectures
    type: object
    default:
      - aarch64
      - amd64
      - amd64-cuda
      - jetson-nano
      - rpi3
  - name: image
    type: string

strategy:
  matrix:
    ${{ each architecture in parameters.architectures }}:
      ${{ architecture }}:
        architecture: ${{ architecture }}

jobs:
  - template: build.yaml
    parameters:
      architecture: $(architecture)
      image: ${{ parameters.image }}
