trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - requirements.txt
pr: none

pool:
  vmImage: "ubuntu-latest"

resources:
  pipelines:
    - pipeline: viserontools
      source: "Viseron tools"
      trigger:
        branches:
          - dev

jobs:
  - template: templates/build.yaml
    parameters:
      image: wheels
