trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

resources:
  pipelines:
    - pipeline: viseronFFmpeg
      source: "Viseron FFmpeg"
      trigger:
        branches:
          - dev

jobs:
  - template: templates/build.yaml
    parameters:
      architectures:
        - aarch64
        - amd64
        - amd64-cuda
        - rpi3
      images:
        - opencv
  - template: templates/build.yaml
    parameters:
      architectures:
        - jetson-nano
      images:
        - opencv-part1
        - opencv
