trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

resources:
  pipelines:
    - pipeline: viseronOpenCV
      source: "Viseron OpenCV"
      trigger:
        branches:
          - dev

jobs:
  - template: templates/multi-arch-build.yaml
    parameters:
      image: dlib
